<?php
/**
 * actions/view_report.php
 * Streams PDF report inline so browser can open it in a new tab.
 */

session_start();

// Check admin session
if (!isset($_SESSION['admin_email']) || empty($_SESSION['admin_email'])) {
    http_response_code(401);
    die('Unauthorized: Session expired. Please login again.');
}

$reportId = isset($_GET['id']) ? (int)$_GET['id'] : 0;
if ($reportId <= 0) {
    http_response_code(400);
    die('Invalid report ID.');
}

require_once __DIR__ . '/../config/db.php';

try {
    if (!isset($conn) || !($conn instanceof mysqli)) {
        throw new Exception('Database connection failed');
    }

    // Select columns; report_html is optional in older schemas
    $stmt = $conn->prepare("SELECT id, test_link, execution_date, pdf_path, COALESCE(report_html, '') AS report_html FROM test_reports WHERE id = ? LIMIT 1");
    if (!$stmt) {
        throw new Exception('Prepare statement failed: ' . $conn->error);
    }

    $stmt->bind_param('i', $reportId);
    $stmt->execute();
    $result = $stmt->get_result();

    if (!$result || $result->num_rows === 0) {
        $stmt->close();
        http_response_code(404);
        die('Report not found.');
    }

    $report = $result->fetch_assoc();
    $stmt->close();

    $candidatePath = '';
    // prefer pdf_path if present
    if (!empty($report['pdf_path'])) {
        $candidatePath = ltrim($report['pdf_path'], '/');
    }

    // prefer report_html if present and pdf not available
    if (empty($candidatePath) && !empty($report['report_html'])) {
        $candidatePath = ltrim($report['report_html'], '/');
    }

    // If still no candidate path stored in DB, attempt to locate generated HTML/PDF in reports/generated by filename containing the report id
    if (empty($candidatePath)) {
        $generatedDir = realpath(__DIR__ . '/../reports/generated');
        if ($generatedDir && is_dir($generatedDir)) {
            // Prefer files that include the report id but avoid matching short numeric substrings by requiring an underscore or word boundary around id
            $patterns = ["{$generatedDir}/*_{$reportId}_*.pdf", "{$generatedDir}/*_{$reportId}_*.html", "{$generatedDir}/*_{$reportId}_*.htm", "{$generatedDir}/*{$reportId}*.pdf", "{$generatedDir}/*{$reportId}*.html"];
            foreach ($patterns as $pattern) {
                foreach (glob($pattern) as $pathMatch) {
                    if (is_file($pathMatch)) {
                        // Use the first matching artifact
                        $candidatePath = ltrim(str_replace(realpath(__DIR__ . '/..') . DIRECTORY_SEPARATOR, '', realpath($pathMatch)), DIRECTORY_SEPARATOR);
                        break 2;
                    }
                }
            }
        }
    }

    if (empty($candidatePath)) {
        http_response_code(404);
        die('No report artifact available for this report.');
    }

    $fullPath = __DIR__ . '/../' . $candidatePath;
    if (!file_exists($fullPath)) {
        http_response_code(404);
        die('Report file not found.');
    }

    $realPath = realpath($fullPath);
    $reportsDir = realpath(__DIR__ . '/../reports');
    if ($realPath === false || $reportsDir === false || strpos($realPath, $reportsDir) !== 0) {
        http_response_code(403);
        die('Access denied: Invalid file path.');
    }

    if (!is_readable($realPath)) {
        http_response_code(403);
        die('Report file is not readable.');
    }

    $ext = strtolower(pathinfo($realPath, PATHINFO_EXTENSION));
    $mime = 'application/octet-stream';
    $disposition = 'inline';
    if ($ext === 'pdf') {
        $mime = 'application/pdf';
    } elseif ($ext === 'html' || $ext === 'htm') {
        $mime = 'text/html; charset=utf-8';
    }

    header('Content-Type: ' . $mime);
    header('Content-Disposition: ' . $disposition . '; filename="' . basename($realPath) . '"');
    header('Content-Length: ' . filesize($realPath));
    header('Cache-Control: public, must-revalidate, max-age=0');
    header('Pragma: public');
    header('Expires: 0');

    readfile($realPath);
    exit;

} catch (Exception $e) {
    http_response_code(500);
    die('Error: ' . $e->getMessage());
} finally {
    if (isset($conn)) {
        $conn->close();
    }
}
?>