<?php
/**
 * setup/insert_test_reports.php
 * Helper script to insert sample test reports for testing the View Reports module
 * This is optional and only needed for testing before you have real reports
 */

require_once __DIR__ . '/../config/db.php';

// Sample test links
$testLinks = [
    'https://www.google.com',
    'https://www.github.com',
    'https://www.stackoverflow.com',
    'https://www.wikipedia.org',
    'https://www.example.com',
];

// Sample PDF paths (these would be generated by your test system)
$samplePdfPaths = [
    'reports/test_report_20260315_100000.pdf',
    'reports/test_report_20260315_110000.pdf',
    'reports/test_report_20260315_120000.pdf',
    'reports/test_report_20260315_130000.pdf',
    'reports/test_report_20260315_140000.pdf',
];

try {
    if (!isset($conn) || !($conn instanceof mysqli)) {
        throw new Exception('Database connection failed');
    }

    $inserted = 0;
    $errors = [];

    // Insert sample data
    $stmt = $conn->prepare("
        INSERT INTO test_reports (test_link, execution_date, pdf_path, status, created_at)
        VALUES (?, ?, ?, ?, NOW())
    ");

    if (!$stmt) {
        throw new Exception('Prepare statement failed: ' . $conn->error);
    }

    // Sample statuses
    $statuses = ['Completed', 'Completed', 'Completed', 'Completed', 'Completed'];

    for ($i = 0; $i < count($testLinks); $i++) {
        $link = $testLinks[$i];
        $pdfPath = $samplePdfPaths[$i];
        $executionDate = date('Y-m-d H:i:s', strtotime("-" . ($i * 10) . " minutes"));
        $status = $statuses[$i];

        $stmt->bind_param('ssss', $link, $executionDate, $pdfPath, $status);

        if ($stmt->execute()) {
            $inserted++;
        } else {
            $errors[] = "Failed to insert: $link - " . $stmt->error;
        }
    }

    $stmt->close();

    echo "<h3>Sample Data Insertion Result</h3>";
    echo "<p><strong>Inserted: $inserted records</strong></p>";

    if (!empty($errors)) {
        echo "<h4>Errors:</h4>";
        echo "<ul>";
        foreach ($errors as $error) {
            echo "<li>" . htmlspecialchars($error) . "</li>";
        }
        echo "</ul>";
    }

    // Fetch and display current data
    $result = $conn->query("SELECT COUNT(*) as total FROM test_reports");
    if ($result) {
        $row = $result->fetch_assoc();
        echo "<p><strong>Total records in test_reports: " . $row['total'] . "</strong></p>";
    }

} catch (Exception $e) {
    echo "<div style='color: red;'>";
    echo "<h3>Error</h3>";
    echo "<p>" . htmlspecialchars($e->getMessage()) . "</p>";
    echo "</div>";
}

$conn->close();
?>
<style>
    body {
        font-family: Arial, sans-serif;
        margin: 2rem;
        background: #f5f5f5;
    }
    h3, h4 {
        color: #333;
    }
    ul {
        background: #fff;
        padding: 1rem;
        border-left: 3px solid #dc3545;
    }
</style>
